# GitHub action to publish assets for release when a tag is created.
# This action runs on any tag that matches "v*" (e.g., v0.1.0).
# Ensure your GPG private key and passphrase are set in the `GPG_PRIVATE_KEY` and `PASSPHRASE` secrets.

name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch full history for GoReleaser changelog
        run: git fetch --prune --unshallow
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Import GPG key
        id: import_gpg  # Add an ID to reference this step's outputs
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for publishing the release

